### Help

Recent technical advances in high-resolution mass spectrometry (MS) have made metabolomics experiments commonplace for a wide variety of disciplines. In most studies, a database search is performed to translate mass signals into concrete metabolites, and to further interpret the data in a biological and genomic context. However, this annotation approach is limited by the size of database, therefore many detected mass signals are classified as unknowns without being further considered. OligoNet implements an alternative method to annotate metabolomics data based on the assumption that some higher-molecular-weight "unknowns" are combinations of repeated subunits (residues). The current version of the web server is dedicated to provide putative annotations of peptides in full scan direct infusion MS or LC/GC-MS data. For this purpose, OligoNet attempts to decompose each mass input into a combination(s) of [17 proteinogenic amino acids](https://github.com/daniellyz/OligoNet/blob/master/amino-acid-full.txt). It requests the third-party web server [DECOMP](https://bibiserv2.cebitec.uni-bielefeld.de/decomp) for a rapid decomposition. Compared to DECOMP, OligoNet provides more user-friendly ouputs for metabolomic experiments, including tje display of decomposition results on the web interface, parallel KEGG database annotation, visualization of annotated peptides in KEGG metabolic network and recording results in a excel table.OligoNet provides an additional network-based visualization of decomposition results named "Peptide degradation network" (PDN). Inspired from the previously-published [Kendrick analogous mass difference network](https://www.ncbi.nlm.nih.gov/pubmed/22006638), the ab initio PDN infers all potential hydrolysis reactions (edges) between peptides (nodes). For instance, the mass signal that is decomposed into two alanines and two prolines (abbreviated as A2P2) is connected to "A2" in the network since A2 can be produced in a biological system by the hydrolysis of A2P2.
### Notice
OligoNet is primary developed for processing mass spectrometry data that are already annotated to elemental formula (theoritical masses)  or measured from ultra-high-resolution mass spectrometer with high mass accuracy. 
### Step A: Upload metabolomics data
File 1 is the mass spectrum data in .txt format. The data file must organized as it is shown in table 1 with first row as headers. The columns must be separated by tabulations. The decimal mark must be a comma.$$^1$$ $$^2$$